#!/bin/bash
#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Inspect a single alert by ID

set -e

input=$(cat)
id=$(echo "$input" | jq -r '.id')
podman exec "$MODULE_ID" cscli alerts inspect "$id" --output json
