#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Unban IP address(es) in CrowdSec
# Usage:
#   - action: "unban", ip: "<IP_ADDRESS>" to unban a specific IP
#   - action: "unban_all" to unban all IPs

exec 4>&1
exec 1>&2
set -e

readarray -t input < <(jq -r '.action, .ip')
action=${input[0]:?missing action argument}
ip=${input[1]:?missing ip argument}

if [[ "$action" == "unban" ]]; then
    podman exec ${MODULE_ID} cscli decisions delete -i ${ip}
elif [[ "$action" == "unban_all" ]]; then
    # Unban all IPs
    # Using xargs to parallelize the deletion process for efficiency
    # The command lists all decisions, extracts the IPs, and deletes them in parallel
    # Note: Adjust the -P value in xargs based on system capabilities for optimal performance
    # The counter will be handled more accurately by the bouncer, since a single IP can appear in multiple jails.
    podman exec ${MODULE_ID} cscli decisions list -o json \
        | jq -r '.[].decisions[].value' \
        | podman exec -i ${MODULE_ID} xargs -l -P10 cscli decision delete -i >/dev/null 2>&1
else
    echo "Unknown action: $action" >&2
    exit 1
fi
