#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os


request = json.load(sys.stdin)
ip = request['ip']
action = request['action']
module_id =  os.get["MODULE_ID"]

if action == 'unban':
    agent.run_helper("podman", "exec", module_id, "cscli", "decision", "delete", "-i", ip).check_returncode()
elif action == 'unban_all':
    agent.run_helper("podman", "exec", module_id, "cscli", "decision", "delete", "--all").check_returncode()
else:
    sys.exit(2)