#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
crowdsec_collections = data.get("crowdsec_collections", "crowdsecurity/sshd")

# split , and join comma
crowdsec_collections = crowdsec_collections.split(",")
" ".join(crowdsec_collections)

agent.set_env("CROWDSEC_COLLECTIONS", crowdsec_collections)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
