#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


helo_host = data.get("helo_host", "")
receiver_emails = data.get("receiver_emails", [])
whitelists = data.get("whitelists", [])
bantime =data.get("bantime", "1")
dyn_bantime = data.get("dyn_bantime", True)
disable_online_api = data.get("disable_online_api", True)
ban_local_network = data.get("ban_local_network", False)

# Setup default values
agent.set_env("HELO_HOST", helo_host)
agent.set_env("RECEIVER_EMAILS",",".join(receiver_emails))
agent.set_env("WHITELISTS",",".join(whitelists))
agent.set_env("BANTIME", bantime)
agent.set_env("DYN_BANTIME", dyn_bantime)
agent.set_env("DISABLE_ONLINE_API", disable_online_api)
agent.set_env("BAN_LOCAL_NETWORK", ban_local_network)
