#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


helo_host = data.get("helo_host", "")
receiver_emails = data.get("receiver_emails", [])
whitelists = data.get("whitelists", [])
bantime =data.get("bantime", "1")
dyn_bantime = data.get("dyn_bantime", True)
# crowdsec looks for Env DISABLE_ONLINE_API we need to inverse the value
disable_online_api = False if data.get("enable_online_api", True) else True
ban_local_network = data.get("ban_local_network", False)
group_threshold = data.get("group_threshold", 100)
dynamic_ban_time_advanced = data.get("dynamicBanTimeAdvanced", False)

# Setup default values
agent.set_env("HELO_HOST", helo_host)
agent.set_env("RECEIVER_EMAILS",",".join(receiver_emails))
agent.set_env("WHITELISTS",",".join(whitelists))
agent.set_env("BANTIME", bantime)
agent.set_env("DYN_BANTIME", dyn_bantime)
agent.set_env("DISABLE_ONLINE_API", disable_online_api)
agent.set_env("BAN_LOCAL_NETWORK", ban_local_network)
agent.set_env("GROUP_THRESHOLD", group_threshold)
agent.set_env("DYNAMIC_BAN_TIME_ADVANCED", dynamic_ban_time_advanced)
