#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

action = "remove" if os.getenv("BAN_LOCAL_NETWORK", "True") == "True" else "install"
agent.run_helper("cscli", "parsers", action, "crowdsecurity/whitelists").check_returncode()
