#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2 # Send any output to stderr, to not alter the action response protocol

# Enable and restart the promtail service
systemctl enable "${MODULE_ID}-crowdsec.service"
systemctl stop "${MODULE_ID}-crowdsec.service"
systemctl start "${MODULE_ID}-crowdsec.service"