#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import json
import sys
import socket

hostname = socket.gethostname()
data = json.load(sys.stdin)
new_token = data.get("enroll_instance", "")
token = os.getenv("ENROLL_INSTANCE", "")
if new_token == token:
    # we have no need to register again
    sys.exit(0)

# we save enroll_instance
agent.set_env("ENROLL_INSTANCE",new_token)

online_api = os.getenv("DISABLE_ONLINE_API", "True") == "True"
if new_token and not online_api:
    agent.run_helper("cscli", "console", "--name", hostname, "enroll", "--overwrite", new_token).check_returncode()
