#!/bin/bash
#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# list alerts

set -e

input=$(cat)
limit=$(echo "$input" | jq -r '.limit // "500"')

if [[ "$limit" == "all" ]]; then
    list=$(podman exec "$MODULE_ID" cscli alerts list --all --output json)
else
    list=$(podman exec "$MODULE_ID" cscli alerts list --limit "$limit" --output json)
fi

if [[ $list == 'null' ]]; then
    echo '[]'
else
    echo "$list"
fi
