#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import json
import sys

data = json.load(sys.stdin)
IP = data['IP']

if IP == "all":
    agent.run_helper("cscli", "decisions", "delete", "--all").check_returncode()
else:
    agent.run_helper("cscli", "decisions", "delete", "-i", IP).check_returncode()
