#!/bin/bash
#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# list collections

set -e

list=$(podman exec "$MODULE_ID" cscli collections list --all --output json)

if [[ $list == 'null' ]]; then
    echo '[]'
else
    echo "$list" | jq '.collections // .'
fi
