#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

if [[ ! -f secrets/bouncer_keys_firewall.secret ]]; then
    /usr/bin/mkdir -vp secrets
    /usr/bin/openssl rand -hex 20 > secrets/bouncer_keys_firewall.secret
    chmod 400 secrets/bouncer_keys_firewall.secret
fi
