#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

ports = os.environ["TCP_PORTS"].split(',')


agent.add_public_service(os.environ['MODULE_ID'], [
        str(ports[0]) + "/tcp", # external sftp port
    ])

# Ignore exit code