#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
source /etc/os-release

if [[ -x "$(which crowdsec-firewall-bouncer)" ]]; then
    exit 0 # Skip bouncer installation if executable is already found in PATH
fi

echo "Install the bouncer:"
if [[ "${PLATFORM_ID}" == "platform:el9" ]] ; then
    curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | bash
    dnf install -y crowdsec-firewall-bouncer-nftables
elif [[ "${ID}" == "debian" ]]; then
    curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
    apt-get update
    apt-get -y install crowdsec-firewall-bouncer-nftables
else
    echo "The platform is not compatible, we exit"
    exit 0
fi
