#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
source /etc/os-release

echo "Install the bouncer:"
if [[ "${PLATFORM_ID}" == "platform:el9" ]] ; then
    if dnf list --installed crowdsec-firewall-bouncer-iptables; then
        echo "crowdsec-firewall-bouncer-iptables is already installed"
        exit 0
    fi
    curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | bash
    dnf install -y crowdsec-firewall-bouncer-iptables
elif [[ "${ID}" == "debian" ]]; then
    if dpkg -l crowdsec-firewall-bouncer-iptables; then
        echo "crowdsec-firewall-bouncer-iptables already installed"
        exit 0
    fi
    curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash
    apt-get update
    apt-get -y install crowdsec-firewall-bouncer-iptables
else
    echo "The platform is not compatible, we exit"
    exit 0
fi