#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2 # Send any output to stderr, to not alter the action response protocol

# Run with TEST_MODE=true to generate the initial configuration
mkdir -vp crowdsec_config
podman run -i --rm --replace --name "${MODULE_ID}-init" \
    --log-driver=none \
    --privileged \
    --network=host \
    --env=TEST_MODE=true \
    --volume  ./crowdsec_config:/etc/crowdsec:Z \
    --volume "${MODULE_ID}-data":/var/lib/crowdsec/data:Z \
    --volume "${CROWDSEC_JOURNAL}":/run/log/journal \
    ${CROWDSEC_IMAGE}

install-systemd-units

systemctl enable --now "${MODULE_ID}.service"
systemctl enable --now "${MODULE_ID}-upgrade-hub.timer"

# Install default collections
podman exec -i ${MODULE_ID} cscli hub update
podman exec -i ${MODULE_ID} cscli hub upgrade

podman exec -i ${MODULE_ID} cscli collections install \
    crowdsecurity/apache2 \
    crowdsecurity/base-http-scenarios \
    crowdsecurity/dovecot \
    crowdsecurity/http-cve \
    crowdsecurity/linux \
    crowdsecurity/mariadb \
    crowdsecurity/nextcloud \
    crowdsecurity/nginx \
    crowdsecurity/nginx-proxy-manager \
    crowdsecurity/pgsql \
    crowdsecurity/postfix \
    crowdsecurity/proftpd \
    crowdsecurity/sshd \
    crowdsecurity/traefik \
    crowdsecurity/vsftpd \
    crowdsecurity/wordpress \
    crowdsecurity/whitelist-good-actors

# we need it if we want to ban with IP from country
podman exec -i ${MODULE_ID} cscli parsers install crowdsecurity/geoip-enrich
