#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2 # Send any output to stderr, to not alter the action response protocol

install -m 644 "${AGENT_INSTALL_DIR}/crowdsec.service" "/etc/systemd/system/${MODULE_ID}.service"

# create the service to update the crowdsec hub for collections
tmpfile=$(mktemp)
trap "rm -f \${tmpfile}" EXIT
cat <<EOF >${tmpfile}
[Unit]
Description=Update the crowdsec HUB
Requisite=${MODULE_ID}.service

[Service]
Type=oneshot
ExecStart=/usr/bin/podman exec -ti crowdsec1 cscli hub update
ExecStart=/usr/bin/podman exec -ti crowdsec1 cscli hub upgrade
SyslogIdentifier=%N
EOF
install -v -m 644 "${tmpfile}" /etc/systemd/system/${MODULE_ID}-upgrade-hub.service

# create the timer to update the crowdsec hub for collections
tmpfile=$(mktemp)
trap "rm -f \${tmpfile}" EXIT
cat <<EOF >${tmpfile}
[Unit]
Description=Timer of crowdsec hub update

[Timer]
OnActiveSec=15 minutes
OnUnitInactiveSec=15 days

[Install]
WantedBy=timers.target
EOF
install -v -m 644 "${tmpfile}" /etc/systemd/system/${MODULE_ID}-upgrade-hub.timer

systemctl daemon-reload
systemctl enable --now "${MODULE_ID}.service"
systemctl enable --now "${MODULE_ID}-upgrade-hub.timer"

# Install default collections
podman exec -ti ${MODULE_ID} cscli hub update
podman exec -ti ${MODULE_ID} cscli hub upgrade

podman exec -ti ${MODULE_ID} cscli collections install \
    crowdsecurity/apache2 \
    crowdsecurity/base-http-scenarios \
    crowdsecurity/dovecot \
    crowdsecurity/http-cve \
    crowdsecurity/linux \
    crowdsecurity/mariadb \
    crowdsecurity/nextcloud \
    crowdsecurity/nginx \
    crowdsecurity/nginx-proxy-manager \
    crowdsecurity/pgsql \
    crowdsecurity/postfix \
    crowdsecurity/proftpd \
    crowdsecurity/sshd \
    crowdsecurity/traefik \
    crowdsecurity/vsftpd \
    crowdsecurity/wordpress
# TODO https://hub.crowdsec.net/author/crowdsecurity/collections/whitelist-good-actors
#podman exec -ti ${MODULE_ID} cscli collections install crowdsecurity/whitelist-good-actors
podman exec -ti ${MODULE_ID} cscli postoverflows install crowdsecurity/rdns
podman exec -ti ${MODULE_ID} cscli parsers install crowdsecurity/geoip-enrich
