#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

if [[ ! -d ${AGENT_STATE_DIR}/secrets/ ]]; then
    /usr/bin/mkdir -p ${AGENT_STATE_DIR}/secrets
fi

if [[ ! -f ${AGENT_STATE_DIR}/secrets/bouncer_keys_firewall.secret ]]; then
    bouncer_keys_firewall=$(/usr/bin/openssl rand -hex 20)
    /usr/bin/echo "$bouncer_keys_firewall" > ${AGENT_STATE_DIR}/secrets/bouncer_keys_firewall.secret
    chmod 400 ${AGENT_STATE_DIR}/secrets/bouncer_keys_firewall.secret
fi
