#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# set -e

# exec 1>&2 # Send any output to stderr, to not alter the action response protocol



# if [[ ! -f ${AGENT_STATE_DIR}/secrets/server.pem ]]; then
#     hostname=$(/usr/bin/hostname)

#     umask 077
#     # Override redis-exec "privileged=True"
#     export REDIS_USER=default

#     mtraefik=$(redis-exec GET "node/${NODE_ID}/default_instance/traefik")

#     redis-exec HGET "module/${mtraefik}/certificate/${MAIL_HOSTNAME}" key | base64 -d > server.key
#     redis-exec HGET "module/${mtraefik}/certificate/${MAIL_HOSTNAME}" cert | base64 -d > server.pem

#     if [[ $(head -c 5 server.key) != '-----' || $(head -c 5 server.pem) != '-----' ]]; then
#         echo "[WARNING] ${service_image} certificate for ${MAIL_HOSTNAME} not found" 1>&2
#         exit 2
#     fi
# fi
