#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2 # never generate action output. Write to stderr instead.
set -e

echo "Create IPSET (ipv4/ipv6) in Firewalld"
firewall-cmd --permanent --new-ipset=crowdsec6-blacklists --type=hash:net --option="timeout=0" --option="maxelem=150000"
firewall-cmd --permanent --new-ipset=crowdsec-blacklists --type=hash:net --option="timeout=0" --option="maxelem=150000"
firewall-cmd --permanent --zone=drop --add-source=ipset:crowdsec-blacklists
firewall-cmd --permanent --zone=drop --add-source=ipset:crowdsec6-blacklists

echo "Restart firewalld"
systemctl restart firewalld

