#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2 # never generate action output. Write to stderr instead.
set -e

echo "Register the localhost bouncer"
secret=$(cat secrets/bouncer_keys_firewall.secret)
podman exec -ti ${MODULE_ID} cscli bouncers add localhost -k "$secret"
