#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import agent
import agent.tasks

from jinja2 import Environment, FileSystemLoader, select_autoescape

files =["/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml"]
for f in files:
    os.remove(f) if os.path.exists(f) else None

jenv = Environment(
    loader=FileSystemLoader(os.getenv("AGENT_INSTALL_DIR")+"/templates"),
    autoescape=select_autoescape(),
    keep_trailing_newline=True,
)

# read secret
f = open(os.environ["AGENT_STATE_DIR"]+"/secrets/bouncer_keys_firewall.secret")
s = f.read()
f.close()

properties = {
    "secret": s
}

json_properties = json.dumps(properties)

template = jenv.get_template('crowdsec-firewall-bouncer.yaml')
output = template.render(json.loads(json_properties))
with open("/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml","w") as f:
    f.write(output)
