#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import agent
import agent.tasks

from jinja2 import Environment, FileSystemLoader, select_autoescape

files =["crowdsec_config/config.yaml.local"]
for f in files:
    try:
        os.remove(f)
    except FileNotFoundError:
        pass

jenv = Environment(
    loader=FileSystemLoader(os.getenv("AGENT_INSTALL_DIR")+"/templates"),
    autoescape=select_autoescape(),
    keep_trailing_newline=True,
)
# placeholder for later
properties = {}

template = jenv.get_template('config.yaml.local')
output = template.render(properties)
with open("crowdsec_config/config.yaml.local","w") as f:
    f.write(output)
