#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2 # Send any output to stderr, to not alter the action response protocol

# create the override of crowdsec-firewall-bouncer
tmpfile=$(mktemp)
trap "rm -f \${tmpfile}" EXIT
cat <<EOF >${tmpfile}
[Unit]
After=${MODULE_ID}.service

[Service]
Restart=always
ExecStartPre=runagent -m ${MODULE_ID} firewall-rules create-ipset
ExecStartPost=runagent -m ${MODULE_ID} firewall-rules add-rule
ExecStopPost=runagent -m ${MODULE_ID} firewall-rules remove-rule
EOF
mkdir -vp /etc/systemd/system/crowdsec-firewall-bouncer.service.d/
install -v -m 644 "${tmpfile}" "/etc/systemd/system/crowdsec-firewall-bouncer.service.d/${MODULE_ID}-override.conf"

# reload and start service
systemctl daemon-reload
systemctl enable --now crowdsec-firewall-bouncer.service
systemctl restart "${MODULE_ID}.service"
