#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Create a wrapper to use the container : cscli metrics

cat <<EOF > /usr/local/sbin/cscli
#!/bin/bash
if [[  -z \$1 ]];then
    echo "
#
# usage : cscli -h
#
"
    exit 0
fi

podman exec -ti ${MODULE_ID} cscli \$@
EOF

chmod a+x /usr/local/sbin/cscli
