#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import agent
import agent.tasks
import sys

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
receiver_emails = data["receiver_emails"]
helo_host = data["helo_host"]
agent.set_env("RECEIVER_EMAILS", receiver_emails)
agent.set_env("HELO_HOST", helo_host)
