{
 "title": "CrowdSec Metrics",
 "description": "Shows the 'cscli metrics' and additional stats to CrowdSec in Grafana",
 "tags": [ "crowdsec" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "appsec_engine",
    "query": {
     "query": "label_values(cs_appsec_reqs_total,appsec_engine)"
    }
   },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(cs_info,instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "cs_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{instance=\"$instance\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw Lines Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{instance=\"$instance\"}[$__range]) or vector(0)) + \nsum(increase(cs_cloudwatch_stream_hits_total{instance=\"$instance\"}[$__range]) or vector(0)) + \nsum(increase(cs_journalctlsource_hits_total{instance=\"$instance\"}[$__range]) or vector(0)) + \nsum(increase(cs_syslogsource_hits_total{instance=\"$instance\"}[$__range]) or vector(0)) +\nsum(increase(cs_dockersource_hits_total{instance=\"$instance\"}[$__range]) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parsed Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok_total{instance=\"$instance\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Whitelisted Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_node_wl_hits_ok_total{instance=\"$instance\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lines Poured to Bucket",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_poured_total{instance=\"$instance\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket Overflows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=\"$instance\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Buckets Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_instantiation_total{instance=\"$instance\"} [$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Scenarios",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, ceil(sum by (name) (increase(cs_bucket_overflowed_total{instance=\"$instance\"}[$__range]))))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Acquisition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, source) (increase(cs_parser_hits_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ source }}"
      },
      {
       "expr": "sum by (source) (increase(cs_parser_hits_ok_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ source }}"
      },
      {
       "expr": "sum by (source) (increase(cs_parser_hits_ko_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ source }}"
      },
      {
       "expr": "sum by (source) (increase(cs_bucket_poured_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ source }}"
      },
      {
       "expr": "sum by (source) (increase(cs_node_wl_hits_ok_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ source }}"
      }
     ]
    }
   ]
  },
  {
   "title": "AppSec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "AppSec Metrics",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (appsec_engine) (increase(cs_appsec_reqs_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ appsec_engine }}"
      },
      {
       "expr": "sum by (appsec_engine) (increase(cs_appsec_block_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ appsec_engine }}"
      }
     ]
    },
    {
     "title": "AppSec '$appsec_engine' Rules Metrics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "repeat": "appsec_engine",
     "targets": [
      {
       "expr": "sum by (rule_name) (increase(cs_appsec_rule_hits{appsec_engine=\"$appsec_engine\", instance=\"$instance\"} [$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Local API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (reason) (cs_alerts{instance=\"$instance\"})",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Decisions",
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (reason, origin, action) (cs_active_decisions{instance=\"$instance\"})",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route, method) (increase(cs_lapi_route_requests_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ route }}"
      }
     ]
    },
    {
     "title": "Bouncers Metrics",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bouncer, route, method) (increase(cs_lapi_bouncer_requests_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ route }}"
      }
     ]
    },
    {
     "title": "Bouncers Decisions",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bouncer) (increase(cs_lapi_decisions_ok_total [$__range]))",
       "legendFormat": "{{ bouncer }}"
      },
      {
       "expr": "sum by (bouncer) (increase(cs_lapi_decisions_ko_total [$__range]))",
       "legendFormat": "{{ bouncer }}"
      }
     ]
    },
    {
     "title": "Machine Metrics",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (machine, route, method) (increase(cs_lapi_machine_requests_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ machine }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(cs_node_hits_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (name) (increase(cs_node_hits_ok_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (name) (increase(cs_node_hits_ko_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Scenarios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (cs_buckets{instance=\"$instance\"})",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum by (name) (increase(cs_bucket_overflowed_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum by (name) (increase(cs_bucket_underflowed_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum by (name) (increase(cs_bucket_instantiation_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum by (name) (increase(cs_bucket_poured_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Whitelists",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name, reason) (increase(cs_node_wl_hits_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum by (name, reason) (increase(cs_node_wl_hits_ok_total{instance=\"$instance\"} [$__range]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lines Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(cs_parser_hits_ok_total{instance=\"$instance\"} [$__rate_interval]))",
     "legendFormat": "Parsed"
    },
    {
     "expr": "sum(rate(cs_parser_hits_ko_total{instance=\"$instance\"} [$__rate_interval]))",
     "legendFormat": "Unparsed"
    },
    {
     "expr": "sum(rate(cs_node_wl_hits_ok_total{instance=\"$instance\"} [$__rate_interval]))",
     "legendFormat": "Whitelisted"
    },
    {
     "expr": "sum(rate(cs_bucket_poured_total{instance=\"$instance\"} [$__rate_interval]))",
     "legendFormat": "Poured"
    }
   ]
  }
 ]
}