#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

install-systemd-units

# enable the Threat Shield timer only if there is a subscription
sync-threat-shield-timer
