#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

install-systemd-units

# enable the timer on instances updating from a version that didn't have it
systemctl enable --now "${MODULE_ID}-import.timer"
