#!/bin/bash
#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Remove the permanent set created by firewalld, we use iptables/ip6tables directly
# Needed to upgrade from crowdsec:1.0.6
find=0
    if [[ -f /etc/firewalld/ipsets/crowdsec-blacklists.xml ]]; then
        firewall-cmd --permanent --delete-ipset=crowdsec-blacklists
        find=1
    fi
    if [[ -f  /etc/firewalld/ipsets/crowdsec6-blacklists.xml ]]; then
        firewall-cmd --permanent --delete-ipset=crowdsec6-blacklists
        find=2
    fi
    if [[ $find -ne 0 ]]; then
        # we need the reload to remove the set from the runtime configuration
        firewall-cmd --reload
        # we need to restart the service to apply the new configuration and create the set with iptables/ip6tables
        systemctl restart crowdsec-firewall-bouncer.service
    fi
