#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# we need to start again to expand configuration
systemctl try-restart "${MODULE_ID}.service" "${MODULE_ID}-firewall-bouncer.service"
