#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2 # Send any output to stderr, to not alter the action response protocol
set -e

source /etc/os-release

echo "Remove the bouncer:"
if [[ "${PLATFORM_ID}" == "platform:el9" ]] ; then
    dnf remove -y crowdsec-firewall-bouncer-nftables
    rm -fv /etc/yum.repos.d/crowdsec_crowdsec.repo
elif [[ "${ID}" == "debian" ]]; then
    apt-get -y remove crowdsec-firewall-bouncer-nftables
    rm -fv /etc/apt/sources.list.d/crowdsec_crowdsec.list
else
    echo "The platform is not compatible, we exit"
    exit 0
fi
