#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

exec 1>&2 # Send any output to stderr, to not alter the action response protocol

rm -f /var/lib/nethserver/cluster/actions/add-module/99restart-crowdsec
rm -f /var/lib/nethserver/cluster/actions/remove-module/99restart-crowdsec
rm -f /var/lib/nethserver/node/actions/add-module/99restart-crowdsec
rm -f /var/lib/nethserver/node/actions/remove-module/99restart-crowdsec
