#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2 # Send any output to stderr, to not alter the action response protocol
set -e

# remove the wrapper to use the container
rm -vf /usr/local/sbin/cscli
# remove residual config
rm -rvf /etc/crowdsec
