#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = {}

# Read current configuration from the environment file
config["helo_host"] = os.getenv("HELO_HOST","")
config["receiver_emails"] = os.getenv("RECEIVER_EMAILS",[])
config["bantime"] = os.getenv("BANTIME",'1m')
config["dyn_bantime"] = os.getenv("DYN_BANTIME",'True') == "True"
config["whitelists"] = os.getenv("WHITELISTS",[])
config["disable_online_api"] = os.getenv("DISABLE_ONLINE_API",'True') == "True"
json.dump(config, fp=sys.stdout)
