#!/bin/bash
#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# list the current banned IP

list=$(podman exec $MODULE_ID cscli decisions list --output json)

if [[ $list == 'null' ]];then
    echo '[]'
else
    echo $list
fi
