name: "Repository initialization"

#
# TODO: it's safe to remove this workflow
#

on:
  push:

jobs:
  initrepo:
    runs-on: ubuntu-latest
    if: github.repository != 'NethServer/ns8-crowdsec' && github.run_number == 1
    steps:
      - uses: actions/checkout@v2

      - run: |
          # Repository initialization
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          modulename=$(basename ${{ github.repository }} | sed 's/^ns8-//')
          if [[ "${modulename}" != "crowdsec" ]]; then
            git mv imageroot/systemd/user/crowdsec.service imageroot/systemd/user/${modulename}.service
            git mv tests/crowdsec.robot tests/${modulename}.robot
            sed -i "s/crowdsec/${modulename}/g" $(find * -type f)
            git rm -f .github/workflows/initialize-repo.yml
          fi
          git commit -a -F - <<EOF
          Repository initialization

          - Enable automated workflows
          - Replace "crowdsec" occurrences with "${modulename}"
          - Rename the service unit file
          EOF
          git push origin ${{ github.ref_name }}
          echo "::notice title=Initialization completed::Now you can clone the repository."
